"use client";
import { Noto_Sans_Thai } from "next/font/google";
import "./globals.css";
import { ToastContainer, Slide } from "react-toastify";
const notoSans = Noto_Sans_Thai({
  subsets: ["latin"],
  weight: ["400"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${notoSans.className} dark`}>
        <ToastContainer
          position="top-right"
          autoClose={5000}
          hideProgressBar={false}
          newestOnTop={false}
          closeOnClick={false}
          rtl={false}
          pauseOnFocusLoss
          draggable
          pauseOnHover
          
          theme="dark"
          transition={Slide}
        />
        {children}
      </body>
    </html>
  );
}
