import { Noto_Sans_Thai } from "next/font/google";
import "./globals.css";

const notoSans = Noto_Sans_Thai({
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${notoSans.className} dark`}
      >
        {children}
      </body>
    </html>
  );
}
